---
kind: Template
apiVersion: v1
metadata:
  name: cert
  annotations:
    description: ${APP_NAME} site deployment, written in Golang
    tags: quickstart,golang,${APP_NAME}
    iconClass: icon-golang
labels:
  template: ${APP_NAME}
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/serving-cert-secret-name: ${APP_NAME}
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 8443
    selector:
      name: ${APP_NAME}
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/dedgar/${APP_NAME}:latest
      from:
        kind: DockerImage
        name: quay.io/dedgar/${APP_NAME}:latest
      importPolicy:
        scheduled: true
      name: "latest"
      referencePolicy:
        type: Source
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${SIDECAR_NAME}
    name: ${SIDECAR_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/dedgar/${SIDECAR_NAME}:latest
      from:
        kind: DockerImage
        name: quay.io/dedgar/${SIDECAR_NAME}:latest
      importPolicy:
        scheduled: true
      name: "latest"
      referencePolicy:
        type: Source
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${SIDECAR_NAME}
        from:
          kind: ImageStreamTag
          name: ${SIDECAR_NAME}:latest
    - type: ConfigChange
    replicas: 1
    selector:
      name: ${APP_NAME}
    template:
      metadata:
        name: ${APP_NAME}
        labels:
          name: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: quay.io/dedgar/${APP_NAME}:v0.0.4
          env:
          - name: PAUSE_ON_START
            value: "false"
          - name: TLS_PORT
            value: ${TLS_PORT}
          - name: APP_DOMAIN
            value: ${APP_DOMAIN}
          - name: CERT_PATH
            value: ${CERT_PATH}
          - name: TLS_FILE_PATH
            value: ${TLS_FILE_PATH}
          - name: SSCS_CERT
            value: ${SSCS_CERT}
          - name: SSCS_KEY
            value: ${SSCS_KEY}
          ports:
          - containerPort: ${TLS_PORT}
          volumeMounts:
          - mountPath: /cert
            name: cert
          - mountPath: /secrets
            name: sscs
        - name: ${SIDECAR_NAME}
          image: quay.io/dedgar/${SIDECAR_NAME}:latest
          env:
          - name: PAUSE_ON_START
            value: "false"
          - name: LEGO_CERT
            value: "true"
          - name: TLS_PORT
            value: ${TLS_PORT}
          - name: CERT_EMAIL
            value: ${CERT_EMAIL}
          - name: APP_DOMAIN
            value: ${APP_DOMAIN}
          - name: CERT_PATH
            value: ${CERT_PATH}
          - name: CERT_SERVER
            value: ${CERT_SERVER}
          - name: TLS_FILE_PATH
            value: ${TLS_FILE_PATH}
          volumeMounts:
          - mountPath: /cert
            name: cert
        volumes:
        - name: cert
          emptyDir: {}
        - name: sscs
          secret:
            secretName: cert
parameters:
- name: APP_DOMAIN
  description: The exposed hostname that will route to the service, and be used with LetsEncrypt 
  value: "[www.dedgar.com]"
- name: TLS_PORT
  description: Port that the application will use to listen for connections
  value: '8443'
- name: CERT_PATH 
  description: The path within the container that will contain the certs from LetsEncrypt
  value: '/cert/'
- name: TLS_FILE_PATH
  description: The directory that will hold the Lego TLS .crt and .key files
  value: '/cert/lego/certificates/'
- name: APP_NAME
  description: The name of the application to run from the start script and pull from the registry
  value: 'cert'
- name: SIDECAR_NAME
  description: The name of the sidecar container that provides the LE certs served by the main web server app
  value: 'pull'
- name: SSCS_CERT
  description: The path to the cert file provided by SSCS
  value: '/secrets/cert.crt'
- name: SSCS_KEY
  description: The path to the key file provided by SSCS
  value: '/secrets/cert.key'